#!/usr/bin/env python3
"""
Generate supabase/functions/_shared/gazetteer.ts from the `zipcodes` dataset.

    pip install zipcodes && python tools/build_gazetteer.py

Why generated rather than hand-written: the first version of the radius gate
was a hand-typed table of ~50 towns. Anything not on it fell through to the
"unresolved" fallback and bought a model call, and one entry ("new york")
swallowed "Western New York" and filed a local job as 292 miles away. A real
gazetteer removes the whole class of problem — and the same dataset gives us
ZIP centroids, so a posting that carries a ZIP resolves exactly instead of by
name.

Scope: every place within RADIUS_KEEP miles of the origin, plus every place in
NEAR_STATES regardless of distance. Far places must be present, not merely
absent — an unrecognized location deliberately passes, so a downstate city that
is missing would slip through rather than be excluded.
"""
import collections
import json
import math
import pathlib

import zipcodes

ORIGIN = (42.8864, -78.8784)   # Buffalo, NY
RADIUS_KEEP = 150              # generous margin around the 50-mile decision
NEAR_STATES = {"NY", "PA"}
OUT = pathlib.Path(__file__).resolve().parents[1] / \
    "supabase/functions/_shared/gazetteer.ts"


def miles(lat, lon):
    r, t = 3958.8, math.radians
    dlat, dlon = t(lat - ORIGIN[0]), t(lon - ORIGIN[1])
    a = (math.sin(dlat / 2) ** 2
         + math.cos(t(ORIGIN[0])) * math.cos(t(lat)) * math.sin(dlon / 2) ** 2)
    return 2 * r * math.asin(math.sqrt(a))


def main():
    rows = zipcodes.list_all()
    by_place = collections.defaultdict(list)
    zip_pts = {}

    for z in rows:
        try:
            la, lo = float(z["lat"]), float(z["long"])
        except (TypeError, ValueError, KeyError):
            continue
        st = z["state"]
        keep_zip = st in NEAR_STATES or miles(la, lo) <= RADIUS_KEEP
        if keep_zip:
            zip_pts[z["zip_code"]] = (la, lo)
        # acceptable_cities are the alternate names an ATS may print for the
        # same place — "Williamsville" for a Buffalo ZIP, and so on.
        for name in [z["city"]] + (z.get("acceptable_cities") or []):
            by_place[(name.strip().lower(), st)].append((la, lo))

    places = {}
    for (name, st), pts in by_place.items():
        la = sum(p[0] for p in pts) / len(pts)
        lo = sum(p[1] for p in pts) / len(pts)
        if st in NEAR_STATES or miles(la, lo) <= RADIUS_KEEP:
            places[f"{name}|{st}"] = [round(la, 4), round(lo, 4)]

    body = f'''// GENERATED by tools/build_gazetteer.py — do not edit by hand.
//
// Source: the `zipcodes` package (US Postal Service data, bundled offline).
// Origin {ORIGIN[0]}, {ORIGIN[1]} (Buffalo, NY).
// Contains every place within {RADIUS_KEEP} miles, plus every place in
// {sorted(NEAR_STATES)} at any distance — far places must be PRESENT to be
// excluded, because an unrecognized location deliberately passes.
//
// {len(places)} place names (including USPS alternate names), {len(zip_pts)} ZIP centroids.

/** "city|ST" -> [lat, lon], averaged over that place's ZIP centroids. */
export const PLACE_COORDS: Record<string, [number, number]> =
  {json.dumps(places, sort_keys=True, separators=(",", ":"))};

/** 5-digit ZIP -> [lat, lon]. A posting carrying a ZIP resolves exactly. */
export const ZIP_COORDS: Record<string, [number, number]> =
  {json.dumps({k: [round(v[0], 4), round(v[1], 4)] for k, v in sorted(zip_pts.items())}, separators=(",", ":"))};
'''
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(pathlib.Path.cwd())}")
    print(f"  places: {len(places)}   zips: {len(zip_pts)}   bytes: {len(body):,}")


if __name__ == "__main__":
    main()
